name: environment-demo

on:
  workflow_dispatch:
  push: 
    tags:
      - '*/*'     

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TestEnvironment        # <-- targeting this environment is what scopes the lookup
    steps:
      - name: Show the environment-scoped var
        run: |
          echo "Value of vars.ENVIRONMENT_VAR: ${{ vars.ENVIRONMENT_VAR }}"
      - name: don't run on push
        run: echo "This doesn't run on simple pushs"
